### PR TITLE
LOLCODE version

### PR DESCRIPTION
**Pull request by erikthered**

### CODE REVIEW

**Comment by nicolasmccurdy** [comment]
:+1: Though I believe you're supposed to print "Swag" first (before the first delay), and are you sure that's a 15 second delay?

**Comment by erikthered** [comment]
There's no sleep/wait in LOLCODE so it's as close as I can get it.

I'll change it to print swag before the first delay.

**Comment by erikthered** [comment]
Is that close enough now?

**Comment by nicolasmccurdy** [comment]
Thanks!

**Pull request merged**
